### PR TITLE
Added Etcher USB Writer

### PR DESCRIPTION
**Pull request by karanrajpal14**

### CODE REVIEW

**Comment by cmoscardi** [comment]
Never seen this before! Looks like a really cool piece of software.

Christian

**Comment by karanrajpal14** [comment]
Yeah. It is. Saves me a lot of time and patience. Most other tools in this space are clunky. Any idea why it isn't building though? Just have a look at the JSON and tell me if I'm doing something wrong there.

**Comment by cmoscardi** [comment]
It's an escape quote thing with the JSON. Changing to this (in the `curl` line):
```
tr -d \\\"
```
worked for me.

The way I debugged this was by running a local server, inspecting the install script, and seeing the \ was missing in that place (the script was just hanging).

So let me know if you want detailed spinup instructions for the local server - it's basically
1. `pip install` from requirements.txt
2. `python packages/seed_packages.py` will seed a local database
3. `python app.py`

**Comment by karanrajpal14** [comment]
My bad. I didn't expect that. I've fixed it and pushed the commit but it still seems to have merge conflicts that I cannot resolve. 

Also, thank you for the instructions. I got it up and running and I'll start digging into Flask since I've never used it. Expect lesser silly mistakes from now on :P

**Comment by karanrajpal14** [comment]
Closing this as it's been resolved in PR #30

**Pull request closed without merging**
