### PR TITLE
Fixed rbenv, google chrome and Go installation

### PR DESCRIPTION
**Pull request by karanrajpal14**
There were a couple of issues with each of these packages that seem to be fixed. Have a look at the commits for more info.

### CODE REVIEW

**Comment by karanrajpal14** [comment]
I'm seeing a couple of issues here apart from my silly mistakes. Might need your help here.
Firstly, the chrome issue. In spite of removing `/etc/apt/sources.list.d/google-chrome.list` I'm still seeing these warning everywhere.
```shell
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/google-chrome.list:3
```
Sure, we could ignore them, but I don't think that's a good idea.

Also, something's up with the headless install of oh-my-zsh. I see this error `/src/test_script.sh: line 132: -z: command not found` in the logs. Any idea what's going wrong @cmoscardi ?

**Comment by karanrajpal14** [comment]
Phew! Done!
I'm installing NVM using git which is easier to deal with. 
[Source](https://github.com/creationix/nvm#git-install)

All the packages (that I've tried) seem to work well now. Except for a few issues that I've raised above.

**Comment by cmoscardi** [comment]
Awesome - thanks for all these fixes.
1. I poked around with the `google-chrome.list` thing once before - I'll take another look.
2. Hm, did not notice that `-z` thing -- it's pure luck that line is working as intended, lol. Also looking into that, I think it should be easy to fix.

**Comment by cmoscardi** [comment]
But with all this looking good, merging + deploying.

**Pull request merged**
