### PR TITLE
[DEBUG] chrome sources

### PR DESCRIPTION
**Pull request by cmoscardi**

### CODE REVIEW

**Comment by cmoscardi** [comment]
Mailspring will probably be down here too. I'll try again later.

**Comment by cmoscardi** [comment]
Fixed with alternative Chrome install method

**Comment by karanrajpal14** [comment]
This issue mainly occurs because Chrome adds it's PPA info in a separate file and so are we. We can either delete the file that Chrome makes, which is what I tried but it didn't go so well.
Or what we can do is directly create that file so that Chrome doesn't have to. That's what I came up with but it wasn't an ideal solution so I didn't go ahead with it.

As long as Chrome can be updated via apt, this solution works as well. Thank you for fixing it @cmoscardi !

**Comment by cmoscardi** [comment]
Yep. According to the chrome docs, the deb adds a PPA during its install.
So I wonder if what was happening was that upon install, the chrome
installer was double-adding it bascially.

Christian

**Comment by karanrajpal14** [comment]
Yeah that's the best possible explanation. Hopefully, it doesn't happen now. 

Also, in case you haven't noticed, the build failed @cmoscardi

**Comment by cmoscardi** [comment]
Yeah thanks. Mailspring kept dying over the weekend with intermittent http
errors. One of the two did succeed. Trying again.

Christian

**Comment by karanrajpal14** [comment]
It did succeed. Not sure why the builds were failing though. I'll get in touch with them if it happens again. You can go ahead and deploy the changes now @cmoscardi

**Pull request closed without merging**
