### PR TITLE
Added Node Version Manager

### PR DESCRIPTION
**Pull request by karanrajpal14**

### CODE REVIEW

**Comment by cmoscardi** [comment]
@karanrajpal14 have they got a logo? If not, maybe use the node.js logo?

**Comment by cmoscardi** [comment]
Oh yeah and to follow up from the email about guidelines for adding logos, can you just commit both the `large` and `48` versions? If you want to run the script to generate the 48 version, that's fine, but if you want to do it some other way that's also fine too... as long as both versions are there.

I'll add something to the readme about this too!

**Comment by karanrajpal14** [comment]
Added the NodeJS icon since these guys don't have their own. I'll add the other icons in a bit.

**Comment by cmoscardi** [comment]
You're the best - thank you!

**Comment by karanrajpal14** [comment]
You're welcome! I have some more applications to add :P will do it next week. Also, this doesn't seem to be showing up on the site. Has it been deployed?

**Comment by cmoscardi** [comment]
Good catch - I forgot to re-seed the database with the latest definitions. Done now!

**Pull request merged**
