### PR TITLE
Added Golang

### PR DESCRIPTION
**Pull request by karanrajpal14**

### CODE REVIEW

**Comment by karanrajpal14** [comment]
Dang! The same error. Any idea why this happens? I'm not even doing anything related to chrome here.

**Comment by karanrajpal14** [comment]
I think I know why this is happening. The issue is similar to oh-my-zsh. This is spawning another shell as well to install the script @cmoscardi

**Comment by cmoscardi** [comment]
Aha! Do you have an idea for a headless install then?

Christian

**Comment by karanrajpal14** [comment]
Not that I'm aware of. It's a script that does the installation. Any other way around it?

**Comment by cmoscardi** [comment]
Hrm. It looks like this specific install script has about 40 stars. I'd worry that it could get stale / go unmaintained. (My rule of thumb is <500 stars means that this project may go stale / not be actively developed or maintained)

Why not just use the method [from the docs](https://golang.org/doc/install)? I don't know much about the Go ecosystem, but it doesn't look too tough.

Or, alternatively, [gvm](https://github.com/moovweb/gvm), which 3000+ stars and looks popular?

**Comment by karanrajpal14** [comment]
@cmoscardi The reason why I did not choose the methods from the doc is that it's difficult to keep it updated. Now that I think about it, the script that I was using previously wasn't going to make this easier as well.

I've switched to a PPA that was mentioned in their docs [here](https://github.com/golang/go/wiki/Ubuntu) 
I think this is a better alternative. 

I wasn't keen on adding gvm because it doesn't look like it's being worked on. There are several features that are missing when compared to NVM and I found too many people facing issues with their installations.

Anyway, all checks have passed and it's running well on my system as well so I guess we can go ahead with it.

**Comment by cmoscardi** [comment]
Excellent! I'll merge and deploy this tomorrow.

**Comment by cmoscardi** [comment]
Hrm. Not clear why github didn't register this from the command line, but it's merged!

**Pull request closed without merging**
